
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules.trainmodel;
import java.text.DecimalFormat;

/**
 *
 * @author bkelly088
 */
public class TrainModelUI extends javax.swing.JFrame {

    private int failures;
    private double trainMass = 40.9;

    
    public TrainModelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        signalFailButton = new javax.swing.JButton();
        brakeFailButton = new javax.swing.JButton();
        eBrakeButton2 = new javax.swing.JButton();
        engineFailButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TrainInfoDisplay1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        velocityLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adText = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        ebrakeLabel = new javax.swing.JLabel();
        speedLimitLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        authLabel = new javax.swing.JLabel();
        passengersLabel = new javax.swing.JLabel();
        leftDLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        rightDLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        sbrakeLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signalFailButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        signalFailButton.setText("Signal Failure");
        signalFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalFailButtonActionPerformed(evt);
            }
        });

        brakeFailButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brakeFailButton.setText("Brake Failure");
        brakeFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brakeFailButtonActionPerformed(evt);
            }
        });

        eBrakeButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eBrakeButton2.setText("Emergency Brake");
        eBrakeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBrakeButton2ActionPerformed(evt);
            }
        });

        engineFailButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        engineFailButton.setText("Engine Failure");
        engineFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineFailButtonActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idLabel.setText("____________");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Train ID:");

        TrainInfoDisplay1.setColumns(20);
        TrainInfoDisplay1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        TrainInfoDisplay1.setRows(5);
        TrainInfoDisplay1.setText("Train 1 Information\n------------------------\nAmount of cars: 2\nNumber of doors: 16\nTrain Length: 32.2m per car\nTrain Width: 2.65m\nTrain Height: 3.42m\nTrain Mass: 40.9T - 56.7T\nMax Capacity: 222 Passengers\nMax Acceleration: 0.5m/s^2\nMax Deceleration: 2.72 m/s^2\nMax Power: 120kW\nMax Speed: 70km/h\n");
        jScrollPane4.setViewportView(TrainInfoDisplay1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Grade:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Passengers:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Speed Limit:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Temperature:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Authority:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Left Doors:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Right Doors:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Service Brake:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Lights:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Emergency Brake:");

        velocityLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        velocityLabel.setText("________");

        adText.setColumns(20);
        adText.setRows(5);
        adText.setText("Advertisements here");
        jScrollPane1.setViewportView(adText);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Current Speed:");

        ebrakeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ebrakeLabel.setText("____________");

        speedLimitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        speedLimitLabel.setText("____________");

        gradeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gradeLabel.setText("____________");

        authLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        authLabel.setText("____________");

        passengersLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengersLabel.setText("____________");

        leftDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        leftDLabel.setText("____________");

        tempLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tempLabel.setText("____________");

        rightDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rightDLabel.setText("____________");

        lightsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lightsLabel.setText("____________");

        sbrakeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sbrakeLabel.setText("____________");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Power:");

        powerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        powerLabel.setText("____________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(10, 10, 10))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(135, 135, 135)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(velocityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ebrakeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sbrakeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(speedLimitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(authLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passengersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(leftDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rightDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lightsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(powerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signalFailButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBrakeButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brakeFailButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineFailButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(engineFailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signalFailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brakeFailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eBrakeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(sbrakeLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(speedLimitLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gradeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(authLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passengersLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leftDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rightDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lightsLabel)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(ebrakeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(powerLabel)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(velocityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(46, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void eBrakeButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.failures = 0;
    }                                             

    private void brakeFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.failures = 1;
    }                                               

    private void signalFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.failures = 2;
    }                                                

    private void engineFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.failures = 3;
    }                                                

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea TrainInfoDisplay1;
    private javax.swing.JTextArea adText;
    private javax.swing.JLabel authLabel;
    private javax.swing.JButton brakeFailButton;
    private javax.swing.JButton eBrakeButton2;
    private javax.swing.JLabel ebrakeLabel;
    private javax.swing.JButton engineFailButton;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel leftDLabel;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JLabel passengersLabel;
    private javax.swing.JLabel powerLabel;
    private javax.swing.JLabel rightDLabel;
    private javax.swing.JLabel sbrakeLabel;
    private javax.swing.JButton signalFailButton;
    private javax.swing.JLabel speedLimitLabel;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel velocityLabel;
    // End of variables declaration                   

    void update(int trainID,double power,double currentSpeed,double grade,int brakes,double speedLimit,int passengers,int lights,double auth,int temp,int doors,String advertisement) {
        trainMass = 40.9 + (.06803885*(passengers+2)); //add passenger weight as well as the required 2 crew members weight to train in tons
        TrainInfoDisplay1.setText("Train Information\n------------------------\nAmount of cars: 2\nNumber of doors: 16\nTrain Length: 32.2m per car\nTrain Width: 2.65m\nTrain Height: 3.42m\nTrain Mass: " + trainMass + "T\nMax Capacity: 222 Passengers\nMax Acceleration: 0.5m/s^2\nMax Deceleration: 2.72 m/s^2\nMax Speed:70km/h\nMax Power 120kW\n");
        adText.setText(advertisement);
        this.velocityLabel.setText(new DecimalFormat("#.##").format(currentSpeed));
        this.passengersLabel.setText(Integer.toString(passengers));
        this.gradeLabel.setText(Double.toString(grade));
        this.powerLabel.setText(Double.toString(power));
        this.speedLimitLabel.setText(Double.toString(speedLimit));
        this.authLabel.setText(Double.toString(auth));
        this.tempLabel.setText(Integer.toString(temp));
        this.idLabel.setText(Integer.toString(trainID));
        
        switch (doors) {
            
            case 0:
                this.leftDLabel.setText("Closed");
                this.rightDLabel.setText("Closed");
                break;
            case 1:
                this.leftDLabel.setText("Open");
                break;
            case 2:
                this.rightDLabel.setText("Closed");
                break;
            case 3:
                this.rightDLabel.setText("Open");
                break;
            default:
                this.leftDLabel.setText("Closed");
                this.rightDLabel.setText("Closed");
                break;
             
    }
        
        switch (brakes) {
            
            case 0:
                this.sbrakeLabel.setText("Off");
                this.ebrakeLabel.setText("Off");
                break;
            case 1:
                this.sbrakeLabel.setText("On");
                break;
            case 2:
                this.ebrakeLabel.setText("Off");
                break;
            case 3:
                this.ebrakeLabel.setText("On");
                break;
            default:
                this.sbrakeLabel.setText("Off");
                this.ebrakeLabel.setText("Off");
                break;
             
    }
        
        switch (lights) {
            
            case 0:
                this.lightsLabel.setText("Off");
                break;
            case 1:
                this.lightsLabel.setText("On");
                break;
            default:
                this.lightsLabel.setText("Off");
                break;
        }
    }
    
    public int getFailures(){
        return this.failures;
    }
	
	public void setFailures(int failures){
        this.failures = failures;
    }
}
