/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules.traincontroller;

import shared.*;

import java.text.DecimalFormat;

/**
 *
 * @author Jen Dudek
 */
public class TestingUI extends javax.swing.JFrame {
    TrainController trainController;
    /**
     * Creates new form TestingUI
     * @param trainController
     */
    public TestingUI(TrainController trainController) {
        this.trainController = trainController;
        trainController.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            @Override
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String event = evt.getPropertyName();
                //System.out.println(event);
                switch (event) {
                    case "currentSpeed": 
                        currentSpeedPropertyChange(evt);
                        break;
                    case "powerUpdate":
                        powerCmdPropertyChange(evt);
                        break;
                    case "metersRemaining":
                        distRemainingPropertyChange(evt);
                        break;
                    case "brakingDist":
                        brakingDistPropertyChange(evt);
                        break;
                    case "station":
                        stationDispPropertyChange(evt);
                        break;
                    case "suggestedSpeed":
                        suggSpeedPropertyChange(evt);
                        break;
                    case "brake":
                        brakePropertyChange(evt);
                        break;    
                    default:
                        break;
                }
            }
        });
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setpointSpeed = new javax.swing.JLabel();
        currentSpeed = new javax.swing.JLabel();
        powerCmd = new javax.swing.JLabel();
        distRemaining = new javax.swing.JLabel();
        brakingDist = new javax.swing.JLabel();
        speed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manual = new javax.swing.JButton();
        automatic = new javax.swing.JButton();
        submitSpeed = new javax.swing.JButton();
        dist = new javax.swing.JTextField();
        submitDist = new javax.swing.JButton();
        modeLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        suggestedSpeed = new javax.swing.JTextField();
        submitSugSpeed = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        suggSpeed = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        advertisement = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stationDisp = new javax.swing.JLabel();
        emergency = new javax.swing.JButton();
        service = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        brake = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Testing UI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Current Speed:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Setpoint Speed:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Power command:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Meters Remaning:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Braking Distance:");

        setpointSpeed.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        setpointSpeed.setText("0");
        setpointSpeed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                setpointSpeedPropertyChange(evt);
            }
        });

        currentSpeed.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        currentSpeed.setText("0.00");
        currentSpeed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currentSpeedPropertyChange(evt);
            }
        });

        powerCmd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        powerCmd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        powerCmd.setText("0");
        powerCmd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                powerCmdPropertyChange(evt);
            }
        });

        distRemaining.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        distRemaining.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        distRemaining.setText("0");
        distRemaining.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                distRemainingPropertyChange(evt);
            }
        });

        brakingDist.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brakingDist.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        brakingDist.setText("0");
        brakingDist.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                brakingDistPropertyChange(evt);
            }
        });

        speed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        speed.setText(" ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Setpoint speed:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Distance til stop:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Mode:");

        manual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manual.setText("Manual");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        automatic.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        automatic.setText("Automatic");
        automatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticActionPerformed(evt);
            }
        });

        submitSpeed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitSpeed.setText("Submit");
        submitSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSpeedActionPerformed(evt);
            }
        });

        dist.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dist.setText(" ");
        dist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distActionPerformed(evt);
            }
        });

        submitDist.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitDist.setText("Submit");
        submitDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDistActionPerformed(evt);
            }
        });

        modeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modeLabel.setText("Automatic");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Suggested speed:");

        suggestedSpeed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        suggestedSpeed.setText(" ");

        submitSugSpeed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitSugSpeed.setText("Submit");
        submitSugSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSugSpeedActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Suggested Speed:");

        suggSpeed.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        suggSpeed.setText("0");
        suggSpeed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                suggSpeedPropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Advertisement:");

        advertisement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advertisement.setText("Dick's Sporting Goods, 50% sale");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Station:");

        stationDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stationDisp.setText(" ");
        stationDisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                stationDispPropertyChange(evt);
            }
        });

        emergency.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emergency.setText("Emergency");
        emergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyActionPerformed(evt);
            }
        });

        service.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        service.setText("Service");
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        service.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                servicePropertyChange(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Brakes:");

        brake.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brake.setText(" ");
        brake.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                brakePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(manual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(automatic, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(8, 8, 8)
                                        .addComponent(advertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stationDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dist))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(suggestedSpeed))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(17, 17, 17)
                                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitSpeed)
                            .addComponent(submitDist)
                            .addComponent(submitSugSpeed)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brake, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(emergency))))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brakingDist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(distRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(powerCmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(setpointSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(suggSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setpointSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suggSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(submitSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(suggestedSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitSugSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(submitDist)
                                .addComponent(dist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(powerCmd))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(distRemaining)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manual)
                            .addComponent(automatic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(brake))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(service)
                            .addComponent(emergency))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(brakingDist))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(stationDisp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(advertisement))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        // TODO add your handling code here:
        modeLabel.setText("Manual");
        trainController.setMode(false);
    }//GEN-LAST:event_manualActionPerformed

    private void distActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distActionPerformed

    private void submitSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSpeedActionPerformed
        // TODO add your handling code here:
        double speed1 = ParseDouble(speed.getText());
        setpointSpeed.setText(speed.getText());
        speed.setText(" ");
        trainController.setVelocityInfo(speed1, 0);
    }//GEN-LAST:event_submitSpeedActionPerformed

    private void submitDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDistActionPerformed
        // TODO add your handling code here:
        double dist1 = ParseDouble(dist.getText());
        distRemaining.setText(dist.getText());
        dist.setText(" ");
        //trainController.setAuthority((int)dist1);
        trainController.setMetersRemaining((int)dist1);
    }//GEN-LAST:event_submitDistActionPerformed

    private void currentSpeedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_currentSpeedPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("currentSpeed")) {
            DecimalFormat numberFormat = new DecimalFormat("#0.00");
            currentSpeed.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }//GEN-LAST:event_currentSpeedPropertyChange

    private void setpointSpeedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_setpointSpeedPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_setpointSpeedPropertyChange

    private void distRemainingPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_distRemainingPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("metersRemaining")) {
            DecimalFormat numberFormat = new DecimalFormat("#0");
            distRemaining.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }//GEN-LAST:event_distRemainingPropertyChange

    private void powerCmdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_powerCmdPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("powerUpdate")) {
            DecimalFormat numberFormat = new DecimalFormat("#0.0000");
            powerCmd.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }//GEN-LAST:event_powerCmdPropertyChange

    private void brakingDistPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_brakingDistPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("brakingDist")) {
            DecimalFormat numberFormat = new DecimalFormat("#0");  
            brakingDist.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }   
    }//GEN-LAST:event_brakingDistPropertyChange

    private void automaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticActionPerformed
        // TODO add your handling code here:
        modeLabel.setText("Automatic");
        trainController.setMode(true);
    }//GEN-LAST:event_automaticActionPerformed

    private void submitSugSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSugSpeedActionPerformed
        // TODO add your handling code here:
        double sugSpeed = ParseDouble(suggestedSpeed.getText());
        trainController.setVelocityInfo(0, sugSpeed);
        suggSpeed.setText(suggestedSpeed.getText());
        suggestedSpeed.setText(" ");
    }//GEN-LAST:event_submitSugSpeedActionPerformed

    private void suggSpeedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_suggSpeedPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("suggestedSpeed")) {
            DecimalFormat numberFormat = new DecimalFormat("#0");  
            suggSpeed.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }//GEN-LAST:event_suggSpeedPropertyChange

    private void stationDispPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_stationDispPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("station")) {  
            stationDisp.setText(String.valueOf(evt.getNewValue()));
        } 
    }//GEN-LAST:event_stationDispPropertyChange

    private void servicePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_servicePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_servicePropertyChange

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        // TODO add your handling code here:
        trainController.setService(true);
        brake.setText("Service");
    }//GEN-LAST:event_serviceActionPerformed

    private void emergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyActionPerformed
        // TODO add your handling code here:
        trainController.setEmergency(true);
        brake.setText("Emergency");
    }//GEN-LAST:event_emergencyActionPerformed

    private void brakePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_brakePropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("brake")) {  
            brake.setText(String.valueOf(evt.getNewValue()));
        }
    }//GEN-LAST:event_brakePropertyChange

    private static double ParseDouble(String strNumber) {
        if (strNumber != null && strNumber.length() > 0) {
            try {
               return Double.parseDouble(strNumber);
            } catch(Exception e) {
               return -1;   // or some value to mark this field is wrong. or make a function validates field first ...
            }
        }
        else return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertisement;
    private javax.swing.JButton automatic;
    private javax.swing.JLabel brake;
    private javax.swing.JLabel brakingDist;
    private javax.swing.JLabel currentSpeed;
    private javax.swing.JTextField dist;
    private javax.swing.JLabel distRemaining;
    private javax.swing.JButton emergency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manual;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JLabel powerCmd;
    private javax.swing.JButton service;
    private javax.swing.JLabel setpointSpeed;
    private javax.swing.JTextField speed;
    private javax.swing.JLabel stationDisp;
    private javax.swing.JButton submitDist;
    private javax.swing.JButton submitSpeed;
    private javax.swing.JButton submitSugSpeed;
    private javax.swing.JLabel suggSpeed;
    private javax.swing.JTextField suggestedSpeed;
    // End of variables declaration//GEN-END:variables
}
