
package modules.traincontroller;
import java.text.DecimalFormat;


import shared.*;
/**
 *
 * @author Jen Dudek
 */
public class TrainControllerUI extends javax.swing.JFrame {
    TrainController trainController;
	private final double MPH_TO_KMH = (double)1.609344;
	private final double KMH_TO_MPH = (double)1/(double)1.609344;
    /**
     * Creates new form TrainControllerUI
     */
    public TrainControllerUI(TrainController trainController) {
        this.trainController = trainController;
        trainController.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            @Override
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String event = evt.getPropertyName();
                //System.out.println(event);
                switch (event) {
                    case "currentSpeed": 
                        currentSpeedPropertyChange(evt);
                        break;
                    case "powerUpdate":
                        powerCmdPropertyChange(evt);
                        break;
                    case "metersRemaining":
                        distRemainingPropertyChange(evt);
                        break;
                    case "brakingDist":
                        //brakingDistPropertyChange(evt);
                        break;
                    case "station":
                        stationDispPropertyChange(evt);
                        break;
                    case "suggestedSpeed":
                        suggSpeedPropertyChange(evt);
                        break;
                    case "brake":
                        brakePropertyChange(evt);
                        break;
                    case "ki":
                        kiDispPropertyChange(evt);
                        break;
                    case "kp":
                        kpDispPropertyChange(evt);
                        break;
					case "speedLimit":
                        speedLimitPropertyChange(evt);
                        break;
					case "doors":
						if ((int)evt.getNewValue() < 2)
							leftDoorsPropertyChange(evt);
						else	
							rightDoorsPropertyChange(evt);
                        break;
					case "failure":	
						failureLabelPropertyChange(evt);
                        break;
                    default:
                        break;
                }
            }
        });
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currentSpeed = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setpointSpeed = new javax.swing.JLabel();
        suggSpeed = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        speed = new javax.swing.JTextField();
        submitSpeed = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        powerCmd = new javax.swing.JLabel();
        distRemaining = new javax.swing.JLabel();
        kiDisp = new javax.swing.JLabel();
        kpDisp = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        speedLimit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        modeLabel = new javax.swing.JLabel();
        manual = new javax.swing.JButton();
        automatic = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        service = new javax.swing.JButton();
        emergency = new javax.swing.JButton();
        brake = new javax.swing.JLabel();
        disable = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rightDoors = new javax.swing.JLabel();
        leftDoors = new javax.swing.JLabel();
        openRight = new javax.swing.JButton();
        openLeft = new javax.swing.JButton();
        closeRight = new javax.swing.JButton();
        closeLeft = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        lights = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        temp = new javax.swing.JTextField();
        tempSubmit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        advertisement = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stationDisp = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        announce = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        failureLabel = new javax.swing.JLabel();
        resetFailure = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ki = new javax.swing.JTextField();
        kp = new javax.swing.JTextField();
        submitKIKP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Train Controller");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train Controller", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 36))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Speed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 28))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Current Speed:");

        currentSpeed.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        currentSpeed.setText("0.00");
        currentSpeed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currentSpeedPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setText("Setpoint Speed:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel10.setText("Suggested Speed:");

        setpointSpeed.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        setpointSpeed.setText("0");
        setpointSpeed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                setpointSpeedPropertyChange(evt);
            }
        });

        suggSpeed.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        suggSpeed.setText("0");
        suggSpeed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                suggSpeedPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setText("Setpoint speed:");

        speed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        speed.setText(" ");

        submitSpeed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitSpeed.setText("Submit");
        submitSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSpeedActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setText("Power command:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setText("Authority:");

        powerCmd.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        powerCmd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        powerCmd.setText("0");
        powerCmd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                powerCmdPropertyChange(evt);
            }
        });

        distRemaining.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        distRemaining.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        distRemaining.setText("0");
        distRemaining.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                distRemainingPropertyChange(evt);
            }
        });

        kiDisp.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        kiDisp.setText("Ki:");
        kiDisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kiDispPropertyChange(evt);
            }
        });

        kpDisp.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        kpDisp.setText("Kp:");
        kpDisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kpDispPropertyChange(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel18.setText("Speed Limit:");

        speedLimit.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        speedLimit.setText("0");
        speedLimit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                speedLimitPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(speedLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(setpointSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(suggSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)))
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(submitSpeed))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(powerCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(distRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kiDisp)
                                .addComponent(kpDisp)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setpointSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suggSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speedLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitSpeed))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kpDisp)
                    .addComponent(jLabel3)
                    .addComponent(powerCmd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kiDisp)
                    .addComponent(jLabel4)
                    .addComponent(distRemaining))
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brakes & Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 28))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel8.setText("Mode:");

        modeLabel.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        modeLabel.setText("Automatic");

        manual.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        manual.setText("Manual");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        automatic.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        automatic.setText("Automatic");
        automatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel12.setText("Brakes:");

        service.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        service.setText("Service");
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        service.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                servicePropertyChange(evt);
            }
        });

        emergency.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        emergency.setText("Emergency");
        emergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyActionPerformed(evt);
            }
        });

        brake.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        brake.setText(" ");
        brake.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                brakePropertyChange(evt);
            }
        });

        disable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        disable.setText("Disable");
        disable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brake, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(disable)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(automatic, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(emergency))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manual)
                    .addComponent(automatic))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(brake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(service)
                    .addComponent(emergency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disable)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 28))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel9.setText("Doors:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Left:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Right:");

        rightDoors.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rightDoors.setText("Closed");

        leftDoors.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        leftDoors.setText("Closed");

        openRight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        openRight.setText("Open");
        openRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRightActionPerformed(evt);
            }
        });

        openLeft.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        openLeft.setText("Open");
        openLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openLeftActionPerformed(evt);
            }
        });

        closeRight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        closeRight.setText("Close");
        closeRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRightActionPerformed(evt);
            }
        });

        closeLeft.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        closeLeft.setText("Close");
        closeLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeLeftActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel16.setText("Lights:");

        lightsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lightsLabel.setText("On");

        lights.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lights.setText("Switch");
        lights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel17.setText("Temp:");

        tempLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tempLabel.setText("70 F");

        temp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        temp.setText(" ");

        tempSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tempSubmit.setText("Submit");
        tempSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempSubmit)
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rightDoors, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(leftDoors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openLeft, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(openRight, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeRight)
                            .addComponent(closeLeft))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lightsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lights)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rightDoors)
                    .addComponent(openRight)
                    .addComponent(closeRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(leftDoors)
                    .addComponent(openLeft)
                    .addComponent(closeLeft))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lightsLabel)
                    .addComponent(lights))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tempLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempSubmit)
                    .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 28))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Advertisement:");

        advertisement.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        advertisement.setText("University of Pittsburgh. Engineering better minds.");
        advertisement.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                advertisementPropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Station:");

        stationDisp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stationDisp.setText(" ");
        stationDisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                stationDispPropertyChange(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Announce:");

        announce.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        announce.setText("Disabled");
        announce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announceActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Failure:");

        failureLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        failureLabel.setText("None.");
        failureLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                failureLabelPropertyChange(evt);
            }
        });

        resetFailure.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetFailure.setText("Reset");
        resetFailure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFailureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stationDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(announce))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(advertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(failureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(resetFailure)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(stationDisp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(announce)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(failureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetFailure))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train Initialization", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Ki:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Kp:");

        ki.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ki.setText(" ");
        ki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiActionPerformed(evt);
            }
        });

        kp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kp.setText(" ");
        kp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpActionPerformed(evt);
            }
        });

        submitKIKP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitKIKP.setText("Submit");
        submitKIKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitKIKPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kp, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(ki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitKIKP)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitKIKP))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void setpointSpeedPropertyChange(java.beans.PropertyChangeEvent evt) {                                             
        // TODO add your handling code here:

    }                                            

    private void currentSpeedPropertyChange(java.beans.PropertyChangeEvent evt) {                                            
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("currentSpeed")) {
            DecimalFormat numberFormat = new DecimalFormat("#0.00");
            currentSpeed.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }                                           

    private void powerCmdPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("powerUpdate")) {
            DecimalFormat numberFormat = new DecimalFormat("#0.00");
            powerCmd.setText(String.valueOf(numberFormat.format(evt.getNewValue())) + " kW");
        }
    }                                       

    private void distRemainingPropertyChange(java.beans.PropertyChangeEvent evt) {                                             
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("metersRemaining")) {
            DecimalFormat numberFormat = new DecimalFormat("#0");
            distRemaining.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }                                            

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        modeLabel.setText("Manual");
        trainController.setMode(false);
    }                                      

    private void automaticActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        modeLabel.setText("Automatic");
        trainController.setMode(true);
    }                                         

    private void submitSpeedActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        double speed1 = ParseDouble(speed.getText());
		DecimalFormat numberFormat = new DecimalFormat("#0");
		if(speed1 > trainController.velocity.speedLimit*KMH_TO_MPH) {
			setpointSpeed.setText(String.valueOf(numberFormat.format(trainController.velocity.speedLimit*KMH_TO_MPH)));
		} else {
			setpointSpeed.setText(String.valueOf(numberFormat.format(speed1)));
		}
        
        speed.setText(" ");
        trainController.setVelocityInfo(speed1 * MPH_TO_KMH, 0);
    }                                           

    private void suggSpeedPropertyChange(java.beans.PropertyChangeEvent evt) {                                         
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("suggestedSpeed")) {
            DecimalFormat numberFormat = new DecimalFormat("#0");
            suggSpeed.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }                                        

    private void stationDispPropertyChange(java.beans.PropertyChangeEvent evt) {                                           
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("station")) {
            stationDisp.setText(String.valueOf(evt.getNewValue()));
        }
    }                                          

    private void emergencyActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        trainController.setEmergency(true);
        brake.setText("Emergency");
    }                                         

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if (!trainController.getMode()){
            trainController.setService(true);
            brake.setText("Service");
        }
    }                                       

    private void servicePropertyChange(java.beans.PropertyChangeEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void brakePropertyChange(java.beans.PropertyChangeEvent evt) {                                     
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("brake")) {
            brake.setText(String.valueOf(evt.getNewValue()));
        }
    }                                    

    private void kiActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void kpActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void submitKIKPActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        double kI = ParseDouble(ki.getText());
        double kP = ParseDouble(kp.getText());
        if (kI >= 0 && kP >= 0)
            trainController.setTrainConstants(kP, kI);
        else
            trainController.setTrainConstants(-1, -1);
			jPanel6.setVisible(false);
			jPanel2.setVisible(true);
			jPanel3.setVisible(true);
			jPanel4.setVisible(true);
			jPanel5.setVisible(true);
    }                                          

    private void kpDispPropertyChange(java.beans.PropertyChangeEvent evt) {                                      
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("kp")) {
            kpDisp.setText("Kp: " + String.valueOf(evt.getNewValue()));
        }
    }                                     

    private void kiDispPropertyChange(java.beans.PropertyChangeEvent evt) {                                      
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("ki")) {
            kiDisp.setText("Ki: " + String.valueOf(evt.getNewValue()));
        }
    }                                     

    private void disableActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        brake.setText(" ");
        trainController.setService(false);
        trainController.setEmergency(false);
    }                                       

    private void openRightActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if (!trainController.getMode()&& trainController.velocity.feedback() == 0) {
            trainController.operateDoors(3);
            rightDoors.setText("Open");
        }
    }                                         

    private void closeRightActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if (!trainController.getMode()) {
            trainController.operateDoors(2);
            rightDoors.setText("Closed");
        }
    }                                          

    private void openLeftActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (!trainController.getMode()&& trainController.velocity.feedback() == 0) {
            trainController.operateDoors(1);
            leftDoors.setText("Open");
        }
    } 

	private void leftDoorsPropertyChange(java.beans.PropertyChangeEvent evt) {                                         
        // TODO add your handling code here:
        if ((int)evt.getNewValue() == 0) {
			leftDoors.setText("Closed");
		} else {
			leftDoors.setText("Open");
		}
    }
	
	private void rightDoorsPropertyChange(java.beans.PropertyChangeEvent evt) {                                         
        // TODO add your handling code here:
		if ((int)evt.getNewValue() == 2) {
			leftDoors.setText("Closed");
		} else {
			leftDoors.setText("Open");
		}
        
    }

    private void closeLeftActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if (!trainController.getMode()) {
            trainController.operateDoors(0);
            leftDoors.setText("Closed");
        }
    }                                         

    private void lightsActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if (!trainController.getMode()) {
            if (lightsLabel.getText().equals("On")) {
                lightsLabel.setText("Off");
                trainController.setLights(false);
            } else {
                lightsLabel.setText("On");
                trainController.setLights(true);
            }
        }
        
        
    }                                      

    private void tempSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if (!trainController.getMode()) {
            double Temp = ParseDouble(temp.getText());
            trainController.setTemp((int)Temp);
            tempLabel.setText(temp.getText() + " F");
            temp.setText(" ");
        }
    }                                          

    private void speedLimitPropertyChange(java.beans.PropertyChangeEvent evt) {                                          
        // TODO add your handling code here:
		if (evt.getPropertyName().equals("speedLimit")) {
			DecimalFormat numberFormat = new DecimalFormat("#0");
            speedLimit.setText(String.valueOf(numberFormat.format(evt.getNewValue())));
        }
    }                                         

    private void announceActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (announce.getText().equals("Enabled")) {
            announce.setText("Disabled");
        } else {
            announce.setText("Enabled");
        }
    }                                        

    private void resetFailureActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
		failureLabel.setText("None.");
		trainController.setFailure(4);
    }                                            

    private void failureLabelPropertyChange(java.beans.PropertyChangeEvent evt) {                                            
        // TODO add your handling code here:
		if (evt.getPropertyName().equals("failure")) {
			if ((int)evt.getNewValue() == 1) {
			failureLabel.setText("Brake failure.");
			} else if ((int)evt.getNewValue() == 2) {
				failureLabel.setText("Signal failure.");
			} else if ((int)evt.getNewValue() == 3) {
				failureLabel.setText("Engine failure.");
			}
		}
		
    }                                           

    private void advertisementPropertyChange(java.beans.PropertyChangeEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    private static double ParseDouble(String strNumber) {
        if (strNumber != null && strNumber.length() > 0) {
            try {
               return Double.parseDouble(strNumber);
            } catch(Exception e) {
               return -1;   // or some value to mark this field is wrong. or make a function validates field first ...
            }
        }
        else return 0;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel advertisement;
    private javax.swing.JToggleButton announce;
    private javax.swing.JButton automatic;
    private javax.swing.JLabel brake;
    private javax.swing.JButton closeLeft;
    private javax.swing.JButton closeRight;
    private javax.swing.JLabel currentSpeed;
    private javax.swing.JButton disable;
    private javax.swing.JLabel distRemaining;
    private javax.swing.JButton emergency;
    private javax.swing.JLabel failureLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField ki;
    private javax.swing.JLabel kiDisp;
    private javax.swing.JTextField kp;
    private javax.swing.JLabel kpDisp;
    private javax.swing.JLabel leftDoors;
    private javax.swing.JButton lights;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JButton manual;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JButton openLeft;
    private javax.swing.JButton openRight;
    private javax.swing.JLabel powerCmd;
    private javax.swing.JButton resetFailure;
    private javax.swing.JLabel rightDoors;
    private javax.swing.JButton service;
    private javax.swing.JLabel setpointSpeed;
    private javax.swing.JTextField speed;
    private javax.swing.JLabel speedLimit;
    private javax.swing.JLabel stationDisp;
    private javax.swing.JButton submitKIKP;
    private javax.swing.JButton submitSpeed;
    private javax.swing.JLabel suggSpeed;
    private javax.swing.JTextField temp;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JButton tempSubmit;
    // End of variables declaration                   
}